### PR TITLE
Added netcat interactive plugin for Faraday

### PR DESCRIPTION
**Pull request by urma**
Added a simple interactive plugin for netcat, which supports the output format of both 'traditional' netcat and OpenBSD's netcat.

### CODE REVIEW

**Comment by Ezequieltbh** [comment]
Excellent work urma!
We tried it and found that does not support GNU Netcat, it would be great to do it!
In the next release will be included your plugin.
Thanks and regards!

**Comment by urma** [comment]
Hi Ezequieltbh
That's great to hear. Could you provide me samples of the output of GNU netcat (on both versions I tested, it was always on the first line when using `nc -v`) so I can double check my regexps? They might be too restrictive.
Thanks!

**Comment by Ezequieltbh** [comment]
~/ ❯❯❯ nc localhost 9977 -v                                                                                                                                                                                                  localhost [127.0.0.1] 9977 open

The first line contains information about host and port, but dont have any service and your regex need it.
I think it is the problem!
Regards!

**Comment by urma** [comment]
I couldn't find a version of netcat which produced the exact same output shown in your sample, so I only tested my updates using mock scripts to emulate its output, but it should now properly handle the lack of a service in the regexp and in the service creation method.
Cheers!

**Comment by Ezequieltbh** [comment]
Now is working, thanks!
In the new version this plugin can be added. 
Cheers!

**Comment by Ezequieltbh** [comment]
Hi urma!
In our last version, we published your plugin.
Thanks for your collaboration, we appreciate that!
Cheers!

**Pull request closed without merging**
