### PR TITLE
Dockerfile added

### PR DESCRIPTION
**Pull request by jamatute**
Added working Dockerfile for the community edition

### CODE REVIEW

**Comment by sangnu** [comment]
Work ok :-) +1

**Comment by Selbstmord-Schafskult** [comment]
Nice!

-------- Original Message --------

**Comment by llazzaro** [comment]
We published a new docker image on docker hub.
We will try to review this pull request for v3.8.
Thank you!

**Comment by kgnfth** [comment]
why is postgresql included in this file ?
its best practice to use postgresql as a seperate container
same goes for the original image https://hub.docker.com/r/faradaysec/faraday

**Comment by kgnfth** [comment]
why did i get a notification about this ? soo strange

**Pull request closed without merging**
