### PR TITLE
ReportHistory

### PR DESCRIPTION
**Pull request by jorexe**
+Added report history view. It displays all vulnerabilities by workspace in a history graph. 
+Added report history button on report view.

### CODE REVIEW

**Comment by Ezequieltbh** [comment]
Hi, Incredible work!
We are working in changes to the WebUi, when finish it your pull request would be merged.
Thanks for the contribution!
Cheers!

**Comment by jorexe** [comment]
Thanks you!. Also we're planning to add some features:
-Filter vulnerabilities by severity.
-Display vulnerabilities by year.

Do you prefer we add those after the merge? or before the merge?

Cheers! Jorge

**Comment by Ezequieltbh** [comment]
Hi @jorexe!
Are you working in this pull request?
I am going to merge this to our project, you need add any commit more?

**Comment by Ezequieltbh** [comment]
Hi!
Due to a lot of changes in our WEB UI and codebase of our backend, this pull request is in a un-mergeable state.
We are going to cherry pick a few commits in the next version to include your new graphs in our project.
Sorry about that, and thanks for contributing to Faraday!
Have a great weekend!

**Pull request closed without merging**
